// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vlriviouictrannhemnh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZscml2aW91aWN0cmFubmhlbW5oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MjM0OTA3MzksImV4cCI6MjAzOTA2NjczOX0.dLHs_si9_pT6NjiJ_1pnjUJtw-MVQEmx_VkNQl8PRQI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);